services:
  manga-reader:
    container_name: kanwoo-backend
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - /home/ivan/kanwoo-backend/.env
    volumes:
      - /var/storage/uploads/:/kanwoo/static/
      - /var/log/kanwoo-backend/:/kanwoo/logs/
