services:
  kanwoo-backend_redis:
    image: redis:latest

  kanwoo-backend:
    image: "cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG"
    restart: always
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DATABASE_URI=$DATABASE_URI
      - CACHE_URI=$CACHE_URI
      - DOMAIN=$DOMAIN
      - MAIL_SERVER=$MAIL_SERVER
      - MAIL_PORT=$MAIL_PORT
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - MAIL_DEFAULT_SENDER=$MAIL_DEFAULT_SENDER
      - COOKIE_DOMAIN=$COOKIE_DOMAIN
      - ACCESS_COOKIE_NAME=$ACCESS_COOKIE_NAME
      - REFRESH_COOKIE_NAME=$REFRESH_COOKIE_NAME
      - ACCESS_CSRF_COOKIE_NAME=$ACCESS_CSRF_COOKIE_NAME
      - REFRESH_CSRF_COOKIE_NAME=$REFRESH_CSRF_COOKIE_NAME
      - AUTH_PROFILE_COOKIE_NAME=$AUTH_PROFILE_COOKIE_NAME
      - UPLOAD_DIR=$UPLOAD_DIR
      - LOG_DIR=$LOG_DIR
      - DOMAIN=$DOMAIN
      - CDN_URL=$CDN_URL
      - FRONTEND_URL=$FRONTEND_URL
      - YANDEX_OAUTH_CLIENT_SECRET=$YANDEX_OAUTH_CLIENT_SECRET
      - YANDEX_OAUTH_LOGIN_URL=$YANDEX_OAUTH_LOGIN_URL
      - YANDEX_AVATARS_URL=$YANDEX_AVATARS_URL
      - YANDEX_AVATARS_SIZE=$YANDEX_AVATARS_SIZE
    ports:
      - "$PORT:8000"
    volumes:
      - $UPLOAD_DIR:/app/kanwoo/static/
      - $LOG_DIR:/app/kanwoo/logs/