services:
  kanwoo-backend_redis:
    image: redis:latest

  kanwoo-backend:
    image: "cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG"
    restart: always
    ports:
      - "$PORT:8000"
    volumes:
      - $UPLOAD_DIR:/app/kanwoo/static/
      - $LOG_DIR:/app/kanwoo/logs/