services:
  redis:
    container_name: kanwoo-backend_redis
    image: redis:latest
    ports:
      - "6379:6379"

  kanwoo-backend:
    container_name: kanwoo-backend
    image: "cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:kanwoo-backend-$IMAGE_TAG"
    restart: always
    ports:
      - "$PORT:8000"
    env:
      CACHE_URI
    volumes:
      - $UPLOAD_DIR:/app/kanwoo/static/
      - $LOG_DIR:/app/kanwoo/logs/