"""empty message

Revision ID: 030463e6348e
Revises: c5af1d6e6dd1
Create Date: 2025-10-14 23:15:58.060137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '030463e6348e'
down_revision = 'c5af1d6e6dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('manga_author', schema=None) as batch_op:
        batch_op.drop_constraint('manga_author_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_author_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=postgresql.ENUM('PRIVATE', 'LINK', 'PUBLIC', name='list_visibility'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
