"""empty message

Revision ID: 0b41fefcdb60
Revises: 5e93e035bc55
Create Date: 2026-07-17 21:17:01.597398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b41fefcdb60'
down_revision = '5e93e035bc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('oauth_user_id', sa.String(), nullable=False))
        batch_op.drop_column('oauth_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_id', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('oauth_user_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
