"""empty message

Revision ID: 1fb8f2b331ef
Revises: ce666bd3c1ac
Create Date: 2026-03-30 19:17:32.765904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fb8f2b331ef'
down_revision = 'ce666bd3c1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('privacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['privacy_id'], ['privacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_manga',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'manga_id')
    )
    op.create_table('collection_save',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'profile_id')
    )
    op.drop_table('list_save')
    op.drop_table('list_manga')
    op.drop_table('list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_manga',
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], name=op.f('list_manga_list_id_fkey')),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('list_manga_manga_id_fkey')),
    sa.PrimaryKeyConstraint('list_id', 'manga_id', name=op.f('list_manga_pkey'))
    )
    op.create_table('list',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('list_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('privacy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], name='list_creator_id_fkey'),
    sa.ForeignKeyConstraint(['privacy_id'], ['privacy.id'], name='list_privacy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='list_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('list_save',
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], name=op.f('list_save_list_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('list_save_user_id_fkey')),
    sa.PrimaryKeyConstraint('list_id', 'user_id', name=op.f('list_save_pkey'))
    )
    op.drop_table('collection_save')
    op.drop_table('collection_manga')
    op.drop_table('collection')
    # ### end Alembic commands ###
