"""empty message

Revision ID: 2530077ec8ff
Revises: 0b41fefcdb60
Create Date: 2026-07-24 15:35:54.314276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2530077ec8ff'
down_revision = '0b41fefcdb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['resolver_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['report_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_table('comment_report',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'report_id')
    )
    op.create_table('manga_comment',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'comment_id')
    )
    op.create_table('chapter_comment',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('chapter_id', 'comment_id')
    )
    with op.batch_alter_table('chapter_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('chapter_report_creator_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('chapter_report_type_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('chapter_report_resolver_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'report', ['report_id'], ['id'])
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('type_id')
        batch_op.drop_column('id')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('resolver_id')
        batch_op.drop_column('comment')

    with op.batch_alter_table('manga_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('manga_report_creator_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('manga_report_type_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('manga_report_resolver_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'report', ['report_id'], ['id'])
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('type_id')
        batch_op.drop_column('id')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('resolver_id')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('resolver_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('manga_report_resolver_id_fkey'), 'profile', ['resolver_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('manga_report_type_id_fkey'), 'report_type', ['type_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('manga_report_creator_id_fkey'), 'profile', ['creator_id'], ['id'])
        batch_op.drop_column('report_id')

    with op.batch_alter_table('chapter_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('resolver_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chapter_report_resolver_id_fkey'), 'profile', ['resolver_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('chapter_report_type_id_fkey'), 'report_type', ['type_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('chapter_report_creator_id_fkey'), 'profile', ['creator_id'], ['id'])
        batch_op.drop_column('report_id')

    op.drop_table('chapter_comment')
    op.drop_table('manga_comment')
    op.drop_table('comment_report')
    op.drop_table('vote')
    op.drop_table('report')
    op.drop_table('comment')
    # ### end Alembic commands ###
