"""empty message

Revision ID: 29b89b5da29a
Revises: 3701ce03e753
Create Date: 2026-02-14 00:16:44.506399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29b89b5da29a'
down_revision = '3701ce03e753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('vote')
    op.drop_table('chapter_comment')
    op.drop_table('manga_comment')
    op.drop_table('comment')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('page_chapter_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('page_chapter_id_fkey'), 'chapter', ['chapter_id'], ['id'])

    op.create_table('chapter_comment',
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('chapter_comment_chapter_id_fkey')),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('chapter_comment_comment_id_fkey')),
    sa.PrimaryKeyConstraint('chapter_id', 'comment_id', name=op.f('chapter_comment_pkey'))
    )
    op.create_table('vote',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('vote_comment_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('vote_user_id_fkey')),
    sa.PrimaryKeyConstraint('comment_id', 'user_id', name=op.f('vote_pkey'))
    )
    op.create_table('manga_comment',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('manga_comment_comment_id_fkey')),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('manga_comment_manga_id_fkey')),
    sa.PrimaryKeyConstraint('manga_id', 'comment_id', name=op.f('manga_comment_pkey'))
    )
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['profile.id'], name=op.f('notification_actor_id_fkey')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('notification_chapter_id_fkey')),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('notification_comment_id_fkey')),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('notification_manga_id_fkey')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('notification_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('root_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('comment_creator_id_fkey')),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name=op.f('comment_parent_id_fkey')),
    sa.ForeignKeyConstraint(['root_id'], ['comment.id'], name=op.f('comment_root_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comment_pkey'))
    )
    # ### end Alembic commands ###
