"""empty message

Revision ID: 366c2324fd3c
Revises: 736ba4fcc2a4
Create Date: 2026-08-12 23:04:27.192500

"""
from alembic import op
import sqlalchemy as sa
from PIL import Image
from config import Config
import os

# revision identifiers, used by Alembic.
revision = '366c2324fd3c'
down_revision = '736ba4fcc2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_subscribe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###

    connection = op.get_bind()

    cursor = connection.execute(sa.text("SELECT uuid, path FROM page;"))
    results = cursor.fetchall()

    for page in results:
        img = Image.open(os.path.join(Config.UPLOAD_DIR, page.path))

        connection.execute(
            sa.text(
                "UPDATE page SET width=:width, height=:height WHERE uuid=:uuid"
            ),    
            {"width": img.width, "height": img.height, "uuid": page.uuid}
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    op.drop_table('translation_subscribe')
    # ### end Alembic commands ###
