"""empty message

Revision ID: 3701ce03e753
Revises: 
Create Date: 2026-02-13 00:09:04.031277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3701ce03e753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'privacy', ['privacy_id'], ['id'])

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'privacy', ['privacy_id'], ['id'])
        batch_op.drop_column('visibility')

    with op.batch_alter_table('manga_name_translation', schema=None) as batch_op:
        batch_op.alter_column('lang_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_name_translation', schema=None) as batch_op:
        batch_op.alter_column('lang_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', postgresql.ENUM('PRIVATE', 'LINK', 'PUBLIC', name='list_visibility'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('privacy_id')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('privacy_id')

    # ### end Alembic commands ###
