"""empty message

Revision ID: 3ba6027574ab
Revises: 711f6acac58d
Create Date: 2026-03-05 19:58:17.646190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba6027574ab'
down_revision = '711f6acac58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profile', ['resolver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resolver_id')

    # ### end Alembic commands ###
