"""empty message

Revision ID: 3bf20f0ccc15
Revises: 639ebacfab3b
Create Date: 2025-11-02 18:16:34.693875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf20f0ccc15'
down_revision = '639ebacfab3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('translation_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('translation_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['creator_id'], ['id'])
        batch_op.drop_column('profile_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('translation_profile_id_fkey', 'profile', ['profile_id'], ['id'])
        batch_op.create_foreign_key('translation_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('creator_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
