"""empty message

Revision ID: 3e1479bc76c2
Revises: 366bd5c2ca5e
Create Date: 2025-10-06 22:19:38.894276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e1479bc76c2'
down_revision = '366bd5c2ca5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_avatar',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'uuid')
    )
    op.drop_table('team_poster')
    with op.batch_alter_table('team_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    op.create_table('team_poster',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('orig_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='team_poster_team_id_fkey'),
    sa.PrimaryKeyConstraint('team_id', 'uuid', name='team_poster_pkey')
    )
    op.drop_table('team_avatar')
    # ### end Alembic commands ###
