"""empty message

Revision ID: 48d2b3c0acb1
Revises: bf3f95d9aed3
Create Date: 2026-03-01 20:06:03.605771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d2b3c0acb1'
down_revision = 'bf3f95d9aed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profile', ['resolver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resolver_id')

    # ### end Alembic commands ###
