"""empty message

Revision ID: 49135b855636
Revises: dc0ee32fee4e
Create Date: 2026-07-07 22:47:36.011918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49135b855636'
down_revision = 'dc0ee32fee4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'oauth_type', ['oauth_type_id'], ['id'])
        batch_op.drop_column('oauth_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('oauth_type_id')

    op.drop_table('oauth_type')
    # ### end Alembic commands ###
