"""empty message

Revision ID: 50bc59b012a3
Revises: ee23b24c5200
Create Date: 2026-07-26 14:19:00.655185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bc59b012a3'
down_revision = 'ee23b24c5200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.drop_column('id_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
