"""empty message

Revision ID: 523b5e7e282c
Revises: 8eff1860409d
Create Date: 2026-02-24 09:49:29.224935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '523b5e7e282c'
down_revision = '8eff1860409d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('manga_author')
    op.drop_table('manga_artist')
    op.drop_table('manga_moderation_status')
    op.drop_table('manga_moderation_status_type')
    op.drop_table('manga_publisher')
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.create_table('manga_publisher',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('manga_publisher_manga_id_fkey')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('manga_publisher_profile_id_fkey'))
    )
    op.create_table('manga_moderation_status_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('manga_moderation_status_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='manga_moderation_status_type_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('manga_moderation_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('manga_moderation_status_manga_id_fkey')),
    sa.ForeignKeyConstraint(['status_type_id'], ['manga_moderation_status_type.id'], name=op.f('manga_moderation_status_status_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('manga_moderation_status_pkey'))
    )
    op.create_table('manga_artist',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('manga_artist_manga_id_fkey')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('manga_artist_profile_id_fkey'))
    )
    op.create_table('manga_author',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name=op.f('manga_author_manga_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], name=op.f('manga_author_user_id_fkey'))
    )
    op.drop_table('manga_suggestion')
    op.drop_table('feedback')
    # ### end Alembic commands ###
