"""empty message

Revision ID: 578a2621da8f
Revises: d960a353a34b
Create Date: 2025-10-09 00:46:39.440717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578a2621da8f'
down_revision = 'd960a353a34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_link', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_link', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
