"""empty message

Revision ID: 5ef18db542aa
Revises: a9590b0e9f1e
Create Date: 2025-09-21 02:21:27.006593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ef18db542aa'
down_revision = 'a9590b0e9f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    list_visibility_enum = postgresql.ENUM('PRIVATE', 'LINK', 'PUBLIC', name='list_visibility')
    list_visibility_enum.create(op.get_bind())

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', list_visibility_enum, nullable=True),)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    list_visibility_enum = postgresql.ENUM('PRIVATE', 'LINK', 'PUBLIC', name='list_visibility')
    list_visibility_enum.drop(op.get_bind())

    # ### end Alembic commands ###
