"""empty message

Revision ID: 60f5d0c2f192
Revises: f198856ab669
Create Date: 2025-09-21 01:11:20.741749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f5d0c2f192'
down_revision = 'f198856ab669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('PRIVATE', 'LINK', 'PUBLIC', name='listvisibility'),
               existing_nullable=True)

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('PRIVATE', 'LINK', 'PUBLIC', name='listvisibility'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
