"""empty message

Revision ID: 628a47157612
Revises: 2f27d9dfc7ad
Create Date: 2026-02-27 22:02:43.467973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628a47157612'
down_revision = '2f27d9dfc7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_moderation_status', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chapter_moderation_status_manga_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['manga_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_moderation_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chapter_moderation_status_manga_id_fkey'), 'manga', ['manga_id'], ['id'])

    # ### end Alembic commands ###
