"""empty message

Revision ID: 639ebacfab3b
Revises: 030463e6348e
Create Date: 2025-10-28 20:31:27.348475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639ebacfab3b'
down_revision = '030463e6348e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_background',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('manga_promo_background',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('manga_promo_logo',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('manga_promo_name',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('manga_save',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'user_id')
    )
    op.drop_table('save')
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_uuid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('background_uuid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('promo_name_uuid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('promo_logo_uuid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('promo_background_uuid', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'manga_promo_name', ['promo_name_uuid'], ['uuid'])
        batch_op.create_foreign_key(None, 'manga_promo_logo', ['promo_logo_uuid'], ['uuid'])
        batch_op.create_foreign_key(None, 'manga_background', ['background_uuid'], ['uuid'])
        batch_op.create_foreign_key(None, 'manga_promo_background', ['promo_background_uuid'], ['uuid'])
        batch_op.create_foreign_key(None, 'manga_poster', ['poster_uuid'], ['uuid'])
        batch_op.drop_column('background')
        batch_op.drop_column('main_poster_number')

    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('manga_poster_manga_id_fkey', type_='foreignkey')
        batch_op.drop_column('manga_id')
        batch_op.drop_column('order')

    with op.batch_alter_table('manga_poster_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('profile_avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('profile_avatar_profile_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['profile_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_avatar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profile_avatar_profile_id_fkey', 'profile', ['profile_id'], ['id'])
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('manga_poster_file', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('manga_poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('manga_poster_manga_id_fkey', 'manga', ['manga_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_poster_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('background', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('promo_background_uuid')
        batch_op.drop_column('promo_logo_uuid')
        batch_op.drop_column('promo_name_uuid')
        batch_op.drop_column('background_uuid')
        batch_op.drop_column('poster_uuid')

    op.create_table('save',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name='save_manga_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='save_user_id_fkey'),
    sa.PrimaryKeyConstraint('manga_id', 'user_id', name='save_pkey')
    )
    op.drop_table('manga_save')
    op.drop_table('manga_promo_name')
    op.drop_table('manga_promo_logo')
    op.drop_table('manga_promo_background')
    op.drop_table('manga_background')
    # ### end Alembic commands ###
