"""empty message

Revision ID: 69f04c338d4a
Revises: f62438f6786d
Create Date: 2026-03-26 15:34:25.412644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f04c338d4a'
down_revision = 'f62438f6786d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_moderation_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('chapter_moderation_status_manga_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'])
        batch_op.drop_column('manga_id')

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'privacy', ['privacy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('privacy_id')

    with op.batch_alter_table('chapter_moderation_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chapter_moderation_status_manga_id_fkey'), 'chapter', ['manga_id'], ['id'])
        batch_op.drop_column('chapter_id')

    # ### end Alembic commands ###
