"""empty message

Revision ID: 711f6acac58d
Revises: 8ff502ce6985
Create Date: 2026-03-05 19:54:25.578263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711f6acac58d'
down_revision = '8ff502ce6985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_suggestion', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_suggestion', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
