"""empty message

Revision ID: 73f28697b9d6
Revises: 1fb8f2b331ef
Create Date: 2026-05-27 21:47:41.979463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f28697b9d6'
down_revision = '1fb8f2b331ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_manga', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('collection_manga_collection_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('collection_manga_manga_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('collection_save', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('collection_save_collection_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('collection_save_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'profile', ['profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('collection_save', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('collection_save_profile_id_fkey'), 'profile', ['profile_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('collection_save_collection_id_fkey'), 'collection', ['collection_id'], ['id'])

    with op.batch_alter_table('collection_manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('collection_manga_manga_id_fkey'), 'manga', ['manga_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('collection_manga_collection_id_fkey'), 'collection', ['collection_id'], ['id'])

    # ### end Alembic commands ###
