"""empty message

Revision ID: 74ec2d446933
Revises: bf3edbdc62ec
Create Date: 2026-03-23 10:30:59.102860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ec2d446933'
down_revision = 'bf3edbdc62ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscriber')
    op.drop_table('avatar')
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('list_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['creator_id'], ['id'])

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profile_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('profile_creator_id_fkey'), 'user', ['creator_id'], ['id'])

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('list_creator_id_fkey'), 'user', ['creator_id'], ['id'])

    op.create_table('avatar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('avatar_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('avatar_pkey'))
    )
    op.create_table('user_subscriber',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], name=op.f('user_subscriber_subscriber_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_subscriber_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'subscriber_id', name=op.f('user_subscriber_pkey'))
    )
    # ### end Alembic commands ###
