"""empty message

Revision ID: 773c68da3967
Revises: 2f75eeaaba32
Create Date: 2026-06-24 13:05:42.653996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773c68da3967'
down_revision = '2f75eeaaba32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('translation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'translation', ['translation_id'], ['id'])
        batch_op.create_foreign_key(None, 'manga', ['manga_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('translation_id')
        batch_op.drop_column('manga_id')

    # ### end Alembic commands ###
