"""empty message

Revision ID: 80ab15242d11
Revises: 0d706235c1b8
Create Date: 2025-09-19 15:18:17.439168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ab15242d11'
down_revision = '0d706235c1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_link',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'type')
    )
    op.create_table('team_permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id', 'rule')
    )
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=16), nullable=False))
        batch_op.drop_column('private')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('visibility')

    op.drop_table('team_permission')
    op.drop_table('team_link')
    # ### end Alembic commands ###
