"""empty message

Revision ID: 89191e103507
Revises: 578a2621da8f
Create Date: 2025-10-09 13:33:04.458827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89191e103507'
down_revision = '578a2621da8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('profile_avatar',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('profile_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'profile_id', 'rule')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('notification_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('notification_team_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('notification_actor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['profile_id'], ['id'])
        batch_op.create_foreign_key(None, 'profile', ['actor_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('translation_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['profile_id'], ['id'])
        batch_op.drop_column('team_id')
        
    op.drop_table('team_member')
    op.drop_table('team_permission')
    op.drop_table('team_link')
    op.drop_table('team_avatar')
    op.drop_table('team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('translation_team_id_fkey', 'team', ['team_id'], ['id'])
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_actor_id_fkey', 'user', ['actor_id'], ['id'])
        batch_op.create_foreign_key('notification_team_id_fkey', 'team', ['team_id'], ['id'])
        batch_op.create_foreign_key('notification_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('profile_id')

    op.create_table('team_avatar',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('orig_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='team_avatar_team_id_fkey'),
    sa.PrimaryKeyConstraint('team_id', 'uuid', name='team_avatar_pkey')
    )
    op.create_table('team_link',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('team_link_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='team_link_team_id_fkey')
    )
    op.create_table('team_permission',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='team_permission_team_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='team_permission_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'team_id', 'rule', name='team_permission_pkey')
    )
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('team_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='team_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='team_pkey'),
    sa.UniqueConstraint('slug', name='team_slug_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('team_member',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='team_member_team_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='team_member_user_id_fkey'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name='team_member_pkey')
    )
    op.drop_table('profile_permission')
    op.drop_table('profile_link')
    op.drop_table('profile_avatar')
    op.drop_table('profile')
    # ### end Alembic commands ###
