"""empty message

Revision ID: 8a4e06412a79
Revises: 
Create Date: 2025-09-21 01:30:35.420373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a4e06412a79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE list SET visibility = UPPER(visibility) WHERE visibility IS NOT NULL")


    list_visibility_enum = postgresql.ENUM('PRIVATE', 'LINK', 'PUBLIC', name='list_visibility')
    list_visibility_enum.create(op.get_bind())

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=16),
               type_=list_visibility_enum,
               existing_nullable=True,
               postgresql_using='visibility::list_visibility')

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=postgresql.ENUM('PRIVATE', 'LINK', 'PUBLIC', name='list_visibility'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    
    list_visibility_enum = postgresql.ENUM('PRIVATE', 'LINK', 'PUBLIC', name='list_visibility')
    list_visibility_enum.drop(op.get_bind())

    # ### end Alembic commands ###
