"""empty message

Revision ID: 8ff502ce6985
Revises: 48d2b3c0acb1
Create Date: 2026-03-03 21:25:48.619419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff502ce6985'
down_revision = '48d2b3c0acb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profile', ['resolver_id'], ['id'])

    with op.batch_alter_table('manga_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profile', ['resolver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resolver_id')

    with op.batch_alter_table('chapter_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resolver_id')

    # ### end Alembic commands ###
