"""empty message

Revision ID: 9b1acf307b1f
Revises: 2a2acf48f24b
Create Date: 2026-02-20 21:04:51.520274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1acf307b1f'
down_revision = '2a2acf48f24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('reading_progress_manga_id_fkey'), type_='foreignkey')
        batch_op.drop_column('manga_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('reading_progress_manga_id_fkey'), 'manga', ['manga_id'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
