"""initial

Revision ID: a9590b0e9f1e
Revises: 
Create Date: 2025-09-21 02:16:28.524792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9590b0e9f1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', postgresql.ENUM('PRIVATE', 'LINK', 'PUBLIC', name='list_visibility'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
