"""empty message

Revision ID: b4cf0115be30
Revises: da8c2536e308
Create Date: 2026-09-28 00:30:25.194670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cf0115be30'
down_revision = 'da8c2536e308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_save', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reading_save_progress', ['manga_id', 'profile_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_save', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reading_save_progress', type_='unique')

    # ### end Alembic commands ###
