"""empty message

Revision ID: bf3edbdc62ec
Revises: 
Create Date: 2026-03-06 15:59:54.098098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3edbdc62ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adult',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_background',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('manga_poster',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('manga_promo_background',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('manga_promo_logo',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('manga_promo_name',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('moderation_status_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privacy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_avatar',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('profile_member_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('avatar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('privacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['privacy_id'], ['privacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_poster_file',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('poster_uuid', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['poster_uuid'], ['manga_poster.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('oauth',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('oauth_type', sa.String(length=20), nullable=False),
    sa.Column('oauth_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('avatar_uuid', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_uuid'], ['profile_avatar.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_subscriber',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'subscriber_id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['resolver_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_save',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'user_id')
    )
    op.create_table('manga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('adult_id', sa.Integer(), nullable=True),
    sa.Column('poster_uuid', sa.String(), nullable=True),
    sa.Column('background_uuid', sa.String(), nullable=True),
    sa.Column('promo_name_uuid', sa.String(), nullable=True),
    sa.Column('promo_logo_uuid', sa.String(), nullable=True),
    sa.Column('promo_background_uuid', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adult_id'], ['adult.id'], ),
    sa.ForeignKeyConstraint(['background_uuid'], ['manga_background.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['poster_uuid'], ['manga_poster.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['privacy_id'], ['privacy.id'], ),
    sa.ForeignKeyConstraint(['promo_background_uuid'], ['manga_promo_background.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promo_logo_uuid'], ['manga_promo_logo.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promo_name_uuid'], ['manga_promo_name.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('manga_suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolver_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['resolver_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_member',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['profile_member_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'user_id')
    )
    op.create_table('profile_permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'profile_id', 'rule')
    )
    op.create_table('list_manga',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'manga_id')
    )
    op.create_table('manga_genre',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], )
    )
    op.create_table('manga_moderation_status',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_type_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['status_type_id'], ['moderation_status_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_name_translation',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.PrimaryKeyConstraint('manga_id')
    )
    op.create_table('manga_report',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['resolver_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['report_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_save',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'user_id')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('privacy_id', sa.Integer(), nullable=True),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['lang_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['privacy_id'], ['privacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tome', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=True),
    sa.Column('privacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['privacy_id'], ['privacy.id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_moderation_status',
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_type_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['status_type_id'], ['moderation_status_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_report',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['resolver_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['report_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('orig_filename', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('reading_progress',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('chapter_id', 'profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_progress')
    op.drop_table('page')
    op.drop_table('chapter_report')
    op.drop_table('chapter_moderation_status')
    op.drop_table('chapter')
    op.drop_table('translation')
    op.drop_table('manga_save')
    op.drop_table('manga_report')
    op.drop_table('manga_name_translation')
    op.drop_table('manga_moderation_status')
    op.drop_table('manga_genre')
    op.drop_table('list_manga')
    op.drop_table('profile_permission')
    op.drop_table('profile_member')
    op.drop_table('profile_link')
    op.drop_table('manga_suggestion')
    op.drop_table('manga')
    op.drop_table('list_save')
    op.drop_table('feedback')
    op.drop_table('user_subscriber')
    op.drop_table('profile')
    op.drop_table('oauth')
    op.drop_table('manga_poster_file')
    op.drop_table('list')
    op.drop_table('avatar')
    op.drop_table('user')
    op.drop_table('type')
    op.drop_table('status')
    op.drop_table('report_type')
    op.drop_table('profile_member_type')
    op.drop_table('profile_avatar')
    op.drop_table('privacy')
    op.drop_table('moderation_status_type')
    op.drop_table('manga_promo_name')
    op.drop_table('manga_promo_logo')
    op.drop_table('manga_promo_background')
    op.drop_table('manga_poster')
    op.drop_table('manga_background')
    op.drop_table('language')
    op.drop_table('genre')
    op.drop_table('adult')
    # ### end Alembic commands ###
