"""empty message

Revision ID: c08d48392eb5
Revises: e61a235f2237
Create Date: 2026-02-25 22:57:02.779485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08d48392eb5'
down_revision = 'e61a235f2237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('manga_promo_background_uuid_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('manga_poster_uuid_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('manga_promo_name_uuid_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('manga_promo_logo_uuid_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('manga_background_uuid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'manga_promo_background', ['promo_background_uuid'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'manga_poster', ['poster_uuid'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'manga_promo_name', ['promo_name_uuid'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'manga_promo_logo', ['promo_logo_uuid'], ['uuid'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'manga_background', ['background_uuid'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_uuid', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'profile_avatar', ['avatar_uuid'], ['uuid'], ondelete='SET NULL')

    with op.batch_alter_table('profile_avatar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profile_avatar_profile_id_fkey'), type_='foreignkey')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('profile_avatar_profile_id_fkey'), 'profile', ['profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('avatar_uuid')

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('manga_background_uuid_fkey'), 'manga_background', ['background_uuid'], ['uuid'])
        batch_op.create_foreign_key(batch_op.f('manga_promo_logo_uuid_fkey'), 'manga_promo_logo', ['promo_logo_uuid'], ['uuid'])
        batch_op.create_foreign_key(batch_op.f('manga_promo_name_uuid_fkey'), 'manga_promo_name', ['promo_name_uuid'], ['uuid'])
        batch_op.create_foreign_key(batch_op.f('manga_poster_uuid_fkey'), 'manga_poster', ['poster_uuid'], ['uuid'])
        batch_op.create_foreign_key(batch_op.f('manga_promo_background_uuid_fkey'), 'manga_promo_background', ['promo_background_uuid'], ['uuid'])

    # ### end Alembic commands ###
