"""empty message

Revision ID: c5af1d6e6dd1
Revises: eea17055759e
Create Date: 2025-10-14 22:01:29.670228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5af1d6e6dd1'
down_revision = 'eea17055759e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint('manga_creator_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['creator_id'], ['id'])

    with op.batch_alter_table('manga_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('manga_artist_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['profile_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('manga_publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('manga_publisher_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['profile_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_publisher_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('manga_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_artist_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manga_creator_id_fkey', 'user', ['creator_id'], ['id'])

    op.create_table('rating',
    sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], name='rating_manga_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='rating_user_id_fkey'),
    sa.PrimaryKeyConstraint('manga_id', 'user_id', name='rating_pkey')
    )
    # ### end Alembic commands ###
