"""empty message

Revision ID: d8acf449f106
Revises: 73f28697b9d6
Create Date: 2026-05-27 22:11:47.912747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8acf449f106'
down_revision = '73f28697b9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profile_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['creator_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('profile_creator_id_fkey'), 'user', ['creator_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
