"""empty message

Revision ID: d960a353a34b
Revises: 3e1479bc76c2
Create Date: 2025-10-07 15:48:39.929199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd960a353a34b'
down_revision = '3e1479bc76c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_link', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
