"""empty message

Revision ID: da8c2536e308
Revises: f5dddc81e880
Create Date: 2026-09-28 00:24:42.407876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8c2536e308'
down_revision = 'f5dddc81e880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_save', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('page')

    # ### end Alembic commands ###
