"""empty message

Revision ID: e61a235f2237
Revises: c6842b9a981a
Create Date: 2026-02-25 22:41:04.945134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61a235f2237'
down_revision = 'c6842b9a981a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.drop_column('ext')

    with op.batch_alter_table('manga_poster_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.drop_column('ext')

    with op.batch_alter_table('manga_promo_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.drop_column('ext')

    with op.batch_alter_table('manga_promo_logo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.drop_column('ext')

    with op.batch_alter_table('manga_promo_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.drop_column('ext')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.drop_column('ext')

    with op.batch_alter_table('profile_avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.drop_column('ext')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_avatar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('path')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('path')

    with op.batch_alter_table('manga_promo_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('path')

    with op.batch_alter_table('manga_promo_logo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('path')

    with op.batch_alter_table('manga_promo_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('path')

    with op.batch_alter_table('manga_poster_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('path')

    with op.batch_alter_table('manga_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('path')

    # ### end Alembic commands ###
