"""empty message

Revision ID: ee23b24c5200
Revises: 2530077ec8ff
Create Date: 2026-07-24 19:04:18.343375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee23b24c5200'
down_revision = '2530077ec8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_creator_id_fkey'), 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###
