"""empty message

Revision ID: f198856ab669
Revises: 366bd5c2ca5e
Create Date: 2025-09-20 21:01:58.385952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f198856ab669'
down_revision = '366bd5c2ca5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('PRIVATE', 'LINK', 'PUBLIC', name='listvisibility'),
               existing_nullable=True)

    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('PRIVATE', 'LINK', 'PUBLIC', name='listvisibility'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
