"""empty message

Revision ID: f5dddc81e880
Revises: 7b50bc8ed6fe
Create Date: 2026-09-26 11:53:33.053702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dddc81e880'
down_revision = '7b50bc8ed6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_save_status_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_save',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['status_type_id'], ['reading_save_status_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False))

    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_finished', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('reading_progress_translation_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reading_progress_manga_id_fkey'), type_='foreignkey')
        batch_op.drop_column('manga_id')
        batch_op.drop_column('translation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translation_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('manga_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('reading_progress_manga_id_fkey'), 'manga', ['manga_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('reading_progress_translation_id_fkey'), 'translation', ['translation_id'], ['id'])
        batch_op.drop_column('is_finished')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('extra_number')

    op.drop_table('reading_save')
    op.drop_table('reading_save_status_type')
    # ### end Alembic commands ###
