"""empty message

Revision ID: f62438f6786d
Revises: 74ec2d446933
Create Date: 2026-03-26 15:29:23.517535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62438f6786d'
down_revision = '74ec2d446933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('manga_privacy_id_fkey'), type_='foreignkey')
        batch_op.drop_column('privacy_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('manga_privacy_id_fkey'), 'privacy', ['privacy_id'], ['id'])

    # ### end Alembic commands ###
