"""empty message

Revision ID: fd8c1f506153
Revises: 3bf20f0ccc15
Create Date: 2025-11-02 20:53:50.174709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8c1f506153'
down_revision = '3bf20f0ccc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint('chapter_creator_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profile', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chapter_creator_id_fkey', 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###
