on:
    workflow_call:
        inputs:
            cr-registry:
                required: true
                type: string
            cr-repository:
                required: true
                type: string
            image-tag:
                required: true
                type: string
        secrets:
            yc-sa-id:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v3

            - name: Login to yandex cloud registry
              uses: yc-actions/yc-cr-login@v3
              with:
                yc-sa-id: ${{ secrets.yc-sa-id }}
                
            - name: Build, tag, and push image to Yandex Cloud Container Registry
              env:
                CR_REGISTRY: ${{inputs.cr-registry}}
                CR_REPOSITORY: ${{inputs.cr-repository}}
                IMAGE_TAG: ${{inputs.image-tag}}
              run: |
                docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
                docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG 
