on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "2.2.1"

      # (необязательно, но полезно) Кэш виртуального окружения Poetry
      - name: Configure Poetry to use in-project venv
        run: poetry config virtualenvs.in-project true

      - name: Install modules
        run: poetry install --no-root

      - name: Test python
        run: poetry run test